------------
-- text-case
-- https://github.com/johmsalas/text-case.nvim#setup
------------

local map = vim.keymap.set
local function config()
	require("textcase").setup({})

	map("n", "gau", function()
		require("textcase").current_word("to_upper_case")
	end)
	map("n", "gal", function()
		require("textcase").current_word("to_lower_case")
	end)
	map("n", "gas", function()
		require("textcase").current_word("to_snake_case")
	end)
	map("n", "gad", function()
		require("textcase").current_word("to_dash_case")
	end)
	map("n", "gan", function()
		require("textcase").current_word("to_constant_case")
	end)
	map("n", "gad", function()
		require("textcase").current_word("to_dot_case")
	end)
	map("n", "gaa", function()
		require("textcase").current_word("to_phrase_case")
	end)
	map("n", "gac", function()
		require("textcase").current_word("to_camel_case")
	end)
	map("n", "gap", function()
		require("textcase").current_word("to_pascal_case")
	end)
	map("n", "gat", function()
		require("textcase").current_word("to_title_case")
	end)
	map("n", "gaf", function()
		require("textcase").current_word("to_path_case")
	end)

	map("n", "gaU", function()
		require("textcase").lsp_rename("to_upper_case")
	end)
	map("n", "gaL", function()
		require("textcase").lsp_rename("to_lower_case")
	end)
	map("n", "gaS", function()
		require("textcase").lsp_rename("to_snake_case")
	end)
	map("n", "gaD", function()
		require("textcase").lsp_rename("to_dash_case")
	end)
	map("n", "gaN", function()
		require("textcase").lsp_rename("to_constant_case")
	end)
	map("n", "gaD", function()
		require("textcase").lsp_rename("to_dot_case")
	end)
	map("n", "gaA", function()
		require("textcase").lsp_rename("to_phrase_case")
	end)
	map("n", "gaC", function()
		require("textcase").lsp_rename("to_camel_case")
	end)
	map("n", "gaP", function()
		require("textcase").lsp_rename("to_pascal_case")
	end)
	map("n", "gaT", function()
		require("textcase").lsp_rename("to_title_case")
	end)
	map("n", "gaF", function()
		require("textcase").lsp_rename("to_path_case")
	end)

	map("n", "geu", function()
		require("textcase").operator("to_upper_case")
	end)
	map("n", "gel", function()
		require("textcase").operator("to_lower_case")
	end)
	map("n", "ges", function()
		require("textcase").operator("to_snake_case")
	end)
	map("n", "ged", function()
		require("textcase").operator("to_dash_case")
	end)
	map("n", "gen", function()
		require("textcase").operator("to_constant_case")
	end)
	map("n", "ged", function()
		require("textcase").operator("to_dot_case")
	end)
	map("n", "gea", function()
		require("textcase").operator("to_phrase_case")
	end)
	map("n", "gec", function()
		require("textcase").operator("to_camel_case")
	end)
	map("n", "gep", function()
		require("textcase").operator("to_pascal_case")
	end)
	map("n", "get", function()
		require("textcase").operator("to_title_case")
	end)
	map("n", "gef", function()
		require("textcase").operator("to_path_case")
	end)
end
return {
	-- change case https://github.com/johmsalas/text-case.nvim
	{
		"johmsalas/text-case.nvim",
		config = config,
		dependencies = {
			"nvim-telescope/telescope.nvim",
		},
	},
}
